### PR TITLE
Enable rust-analyzer to infer `Readable::Output`

### PR DESCRIPTION
**Pull request by qryxip**
Before:
before
After:
after

### CODE REVIEW

**Comment by qryxip** [comment]
We may release v0.3.7, as this change does not affect the actual behavior.

**Comment by qryxip** [comment]
The CI is
> disabled because there hasn't been activity in this repository for at least 60 days.

On the forked one, Clippy jobs are failing for beta toolchains.

https://github.com/qryxip/proconio-rs/runs/2158233114?check_suite_focus=true

**Comment by qryxip** [comment]
#20

**Comment by statiolake** [comment]
Confirmed in Visual Studio Code too:

image

Seems OK to me. I'm not sure but we can expect CI is now good... Let's merge it.

Thank you for this great improvement! I'll backport this to v0.3 branch too.

**Pull request merged**
